quoteProps: as-needed
semi: false
tabWidth: 4
singleQuote: true
printWidth: 9999
bracketSpacing: true
bracketSameLine: true
arrowParens: always
endOfLine: lf
proseWrap: never
singleAttributePerLine: false
trailingComma: none
